spring:
  jackson:
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: LPM Catering
security:
  oauth2:
    client:
          clientId: LPM
          clientSecret: random_secret_4_jay
          accessTokenUri: http://localhost:8080/oauth/token
          userAuthorizationUri: http://localhost:8080/oauth/authorize
          tokenName: LPM_token
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
lpm:
  core:
    url: http://localhost:8081
  storage:
    images:
      products: /tmp/images/products
logging:
  level: debug
server:
  port: 8081
